version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "seabattle"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "strongPassword"
    ports:
      - "5432:5432"
